version: '3'
services:
  backend:
    image: ghcr.io/cs50bookrentalsystem/brsbackend:latest
    container_name: backend
    ports:
      - "8080:8080"

  frontend:
    image: ghcr.io/cs50bookrentalsystem/brsfrontend:latest
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API=http://backend:8080
    depends_on:
      - backend